apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap               
data:
  nginx.cfg: |
    upstream backend {
    server app-1:8080;
    server app-2:8080;
    }

    server {
        location / {
            proxy_pass http://backend;
        }
    }
  default.conf: |
    server {
        listen 80;
        server_name localhost;
        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
        }
    }